version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-west-2:078563635295:task-definition/dev-test-angular:8"
        LoadBalancerInfo:
          ContainerName: "angular"
          ContainerPort: 4200
# Optional properties
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets: ["subnet-037668297a8e1aa36", "subnet-0057fcb76fd91bbcf"]
            SecurityGroups: ["sg-042e8d1cebc77781d"]
            AssignPublicIp: "DISABLED"
Hooks:
  - AfterAllowTestTraffic: "angular_runtests"
